# Generated by Django 3.2.13 on 2022-06-15 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv_builder', '0003_userprofile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workexperience',
            name='end_month',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='end_year',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
