# Generated by Django 3.2.13 on 2022-06-16 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv_builder', '0007_auto_20220616_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationexperience',
            name='end_month',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='educationexperience',
            name='end_year',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
