# Generated by Django 3.2.13 on 2022-06-16 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cv_builder', '0009_alter_language_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cv_builder.userprofile'),
        ),
    ]
