version: "3.3"

services:

  backend:
    build: .
    container_name: backend-2
    command: gunicorn core.wsgi --bind 0.0.0.0:8000
    volumes:
      - ./core:/app
      - static_volume:/app/static
      - media_volume:/app/media

    expose:
      - "8000"
    environment:
      - SECRET_KEY=test
      - DEBUG=False

  
  nginx:
    image: nginx
    container_name: nginx-2
    restart: always
    ports: 
      - "8898:80"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/home/app/static
      - media_volume:/home/app/media
    depends_on:
      - backend


volumes:
  static_volume:
  media_volume: